// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ThaiFontAutoAdjuster","status":true,"description":"ปรับตัวอักษรภาษาไทยไปตามยถากรรม","parameters":{}},
{"name":"CommonEventByStatusAilment","status":true,"description":"Call common event when a status ailment is added to or removed from a player.","parameters":{}}
];
